name: glag_bot

services:
  bot:
    build: .
    env_file: .env
    restart: unless-stopped
    volumes:
      - type: volume
        source: sessions
        target: /var/run/sessions
    logging:
      driver: local
      options:
        max-size: 100m
        max-file: 1000
        compress: "true"

volumes:
  sessions:
